default: ConsoleDebug
level: LogLevel.DEBUG
appenders:
  - name: ConsoleDebug
    appender: console
    pattern: '%d{YYYY-MM-DD HH:mm:ss.SSS} %-7c{[%l]} %10n %5p - %2w  %M'
    level: LogLevel.DEBUG
  - name: FileLog
    appender: file
    pattern: '%d{YYYY-MM-DD HH:mm:ss.SSS} [%l] %10n %5p - %2w  %M'
    level: LogLevel.INFO
    file: relative(file.log)
